part1: part1.c ../include/lib/libaoc.c ../include/lib/libaoc.h
	gcc -I../include -o part1 part1.c ../include/lib/libaoc.c

part2: part1.c ../include/lib/libaoc.c ../include/lib/libaoc.h
	gcc -I../include -o part2 part2.c ../include/lib/libaoc.c

clean:
	@echo "removing files 'part1' and 'part2'"
	@rm part1 part2
